### ISSUE TITLE
qsTr(errmsg)

### ISSUE THREAD

**Issue by mentaljam** [krobelus/cyanide#20]
Hello!

Lupdate gives warnings for **qsTr(errmsg)** in qml files:
_qsTr(): text to translate must be a literal string_

Does it make sense to put **errmsg** variable into **qsTr()**?
I don't know much about programming, so excuse me if my question is stupid)

**Comment by krobelus** [comment]
Yes it makes sense. (maybe there is a better way to do it but it works)

qsTr() does two things: If the argument is a string literal, it is added to the .ts files by lupdate
and at runtime it turns its argument into a translated string if available.

In those cases, errmsg is a string returned by a C++ function.
The possible return strings are wrapped in tr() in the source code so that they too are recognised by lupdate - this way qsTr() is able to translate them.

**Comment by mentaljam** [comment]
I thought that after tr() the C++ function returns already translated strings, doesn't it?

**Comment by krobelus** [comment]
I thought so too but apparently it doesn't - it doesn't translate if i don't use qsTr() iirc

**Comment by mentaljam** [comment]
Thanks for reply! Now it's clear
