### ISSUE TITLE
Use chat/IM notification instead of message/SMS notification

### ISSUE THREAD

**Issue by ghost** [krobelus/cyanide#25]
I'm not sure if these are the right names for the notification sounds, but I think it makes more sense to have Cyanide use the generally shorter notification sound of an IM message than the longer notification sound of an SMS. That way, when you receive lots of messages in a row, the notification sound is less likely to sound garbled.

If this isn't possible, or maybe in addition to this, an option to only notify on the first unread message would be nice, it would solve the notification sound overload problem as well.

**Comment by krobelus** [comment]
Thanks for your feedback, I usually have sounds disabled, so this never occurred to me
I did specify 'chat' as feedback type in the notification file
https://github.com/krobelus/cyanide/blob/master/filesystem/usr/share/lipstick/notificationcategories/harbour.cyanide.message.conf
so this should use jolla-imtone which is the shorter one unless you changed it

But yeah, I will improve the notification handling... The way it is now is that there is at most one notification per friend, which gets created/replaced when another message is received. Instead of publishing another notification, I could probably just update their text.

**Comment by ghost** [comment]
Seems to work fine now!
